# -*- coding: utf-8 -*-
"""Makurdi_ProjectFinal_PhaseA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qey_B8TL5tqZXRokMcoHfXs9t9BrJViK
"""

#import google drive
from google.colab import drive
drive.mount ('/content/drive')
print('Drive connected successfully')

import os

# Create a project folder on your Google Drive
project_folder = "/content/drive/MyDrive/Makurdi_PINN_Project2"
output_dir     = f"{project_folder}/Event_Arrays"
clean_dir      = f"{output_dir}/cleaned"

os.makedirs(output_dir, exist_ok=True)
os.makedirs(clean_dir, exist_ok=True)

print("Paths ready:")
print("output_dir →", output_dir)
print("clean_dir  →", clean_dir)

print(f"Project folder ready at: {project_folder}")

import ee
import geemap

# Trigger authentication flow
ee.Authenticate()

# Initialize Earth Engine
ee.Initialize(project='ganga-region-surface-water-1') # Replace with your GEE Project ID if different
print("Google Earth Engine successfully initialized! 🚀")

import os
import ee
import geemap
import numpy as np

# ---------- Earth Engine (run only once per session) ----------
# ee.Authenticate()          # uncomment if needed
ee.Initialize(project='ganga-region-surface-water-1')   # change if your project ID is different

# ---------- TIGHTER Makurdi reach (recommended) ----------
makurdi_bbox = ee.Geometry.BBox(8.45, 7.68, 8.65, 7.82)
print("Using tighter bounding box:", makurdi_bbox.getInfo())

# Updated DEM asset call
dem_coll = ee.ImageCollection("COPERNICUS/DEM/GLO30_2024_1").select("DEM")
dem_90m = (
    dem_coll.mosaic()
    .clip(makurdi_bbox)
    .setDefaultProjection(crs="EPSG:4326", scale=30)
    .reduceResolution(reducer=ee.Reducer.mean(), maxPixels=1024)
    .reproject(crs="EPSG:4326", scale=90)
)

slope = ee.Terrain.slope(dem_90m)

# ---------- Permanent channel + bathymetry burn ----------
jrc = ee.Image("JRC/GSW1_4/GlobalSurfaceWater").select("occurrence")
river_mask = jrc.gt(80).clip(makurdi_bbox)

channel_depth = ee.Image(4.0).multiply(river_mask)   # metres
dem_burned    = dem_90m.subtract(channel_depth)

# ---------- HAND proxy ----------
local_min = dem_90m.focalMin(radius=500, units="meters")
hand      = dem_90m.subtract(local_min).rename("HAND")

# ---------- Manning’s n ----------
lc = (ee.Image("COPERNICUS/Landcover/100m/Proba-V-C3/Global/2019")
      .select("discrete_classification")
      .clip(makurdi_bbox))

lc_classes     = [80, 50, 111, 112, 113, 114, 115, 116, 40, 30, 20]
manning_values = [35, 80, 100, 100, 100, 100, 100, 100, 50, 40, 50]
manning_n      = (lc.remap(lc_classes, manning_values, 50)
                  .divide(1000.0)
                  .rename("manning_n"))

# ---------- Static multi-band stack ----------
static_stack = ee.Image.cat([
    dem_burned.rename("dem_burned"),
    slope.rename("slope"),
    hand,
    manning_n
])

print("Static stack ready.")

# ============================================================
# CELL 2: Export static stack + extract events (2015–2022)
# ============================================================
from datetime import datetime, timedelta, timezone
import numpy as np

# ---------- Export static stack ----------
print("Exporting static stack …")
static_np = geemap.ee_to_numpy(static_stack, region=makurdi_bbox, scale=90)
np.savez_compressed(
    f"{output_dir}/static_stack_90m.npz",
    dem_burned = static_np[:, :, 0],
    slope      = static_np[:, :, 1],
    hand       = static_np[:, :, 2],
    manning_n  = static_np[:, :, 3]
)
print(f"Static shape: {static_np.shape[:2]}")

# ---------- Sentinel-1 water masks (full 2015–2022) ----------
s1_collection = (ee.ImageCollection("COPERNICUS/S1_GRD")
                 .filterBounds(makurdi_bbox)
                 .filter(ee.Filter.eq("instrumentMode", "IW"))
                 .filter(ee.Filter.listContains("transmitterReceiverPolarisation", "VV"))
                 .filter(ee.Filter.calendarRange(8, 11, "month"))          # wet season
                 .filter(ee.Filter.calendarRange(2015, 2022, "year"))     # ← up to 2022
                 .sort("system:time_start"))

def process_s1_water(img):
    vv = img.select("VV").focalMedian(30, "circle", "meters")
    water = vv.lt(-16.0).rename("sar_water")
    return water.copyProperties(img, ["system:time_start"])

s1_water = s1_collection.map(process_s1_water)

# ---------- Extract events ----------
# Increase the limit so we actually reach 2019–2022
MAX_EVENTS = 80                     # ← raised from 40

s1_list = s1_water.toList(s1_water.size())
total_available = s1_water.size().getInfo()
print(f"Total Sentinel-1 scenes available (2015–2022 wet season): {total_available}")

extracted = 0
for i in range(min(MAX_EVENTS, total_available)):
    try:
        img = ee.Image(s1_list.get(i))
        t_ms = img.get("system:time_start").getInfo()

        # Fixed datetime (no deprecation warning)
        event_dt = datetime.fromtimestamp(t_ms / 1000.0, tz=timezone.utc)
        date_str = event_dt.strftime("%Y_%m_%d")

        start_rain = event_dt - timedelta(days=30)
        chirps = (ee.ImageCollection("UCSB-CHG/CHIRPS/DAILY")
                  .filterBounds(makurdi_bbox)
                  .filterDate(start_rain.strftime("%Y-%m-%d"),
                              event_dt.strftime("%Y-%m-%d"))
                  .sum()
                  .clip(makurdi_bbox))

        sar_np  = geemap.ee_to_numpy(img.select("sar_water"), region=makurdi_bbox, scale=90)
        rain_np = geemap.ee_to_numpy(chirps, region=makurdi_bbox, scale=90)

        np.savez_compressed(
            f"{output_dir}/event_{date_str}.npz",
            sar_water       = sar_np[:, :, 0],
            antecedent_rain = rain_np[:, :, 0]
        )
        extracted += 1
        print(f"[{extracted}/{MAX_EVENTS}] {date_str}")
    except Exception as e:
        print(f"Skipped index {i}: {e}")

print(f"\nFinished – {extracted} events saved.")

# ============================================================
# CELL 3: Clean & resize events
# ============================================================
from scipy.ndimage import zoom
import glob

static = np.load(f"{output_dir}/static_stack_90m.npz")
H, W = static["dem_burned"].shape
print(f"Target grid: {H} × {W}")

event_files = sorted(glob.glob(f"{output_dir}/event_*.npz"))
print(f"Raw events found: {len(event_files)}")

for f in event_files:
    d = np.load(f)
    sar  = d["sar_water"].astype(np.float32)
    rain = d["antecedent_rain"].astype(np.float32)

    zy = H / sar.shape[0]
    zx = W / sar.shape[1]

    sar_r  = zoom(sar,  (zy, zx), order=0)[:H, :W]
    rain_r = zoom(rain, (zy, zx), order=1)[:H, :W]

    if sar_r.shape != (H, W):
        py = H - sar_r.shape[0]
        px = W - sar_r.shape[1]
        sar_r  = np.pad(sar_r,  ((0, py), (0, px)), mode="edge")
        rain_r = np.pad(rain_r, ((0, py), (0, px)), mode="edge")

    sar_r  = np.clip(np.nan_to_num(sar_r, nan=0.0), 0, 1)
    rain_r = np.nan_to_num(rain_r, nan=0.0)

    out = f"{clean_dir}/{os.path.basename(f)}"
    np.savez_compressed(out, sar_water=sar_r, antecedent_rain=rain_r)
    print(f"Cleaned → {os.path.basename(out)}  {sar_r.shape}")

print("\nCleaning complete.")

# ============================================================
# CELL 4: HydroPINN model + training
# ============================================================
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# ---------- Load static features ----------
static_data = np.load(f"{output_dir}/static_stack_90m.npz")
dem_np     = np.nan_to_num(static_data["dem_burned"], nan=100.0)
slope_np   = np.nan_to_num(static_data["slope"],      nan=0.001)
hand_np    = np.nan_to_num(static_data["hand"],       nan=10.0)
manning_np = np.nan_to_num(static_data["manning_n"],  nan=0.05)

dem_norm  = (dem_np  - dem_np.min())  / (dem_np.max()  - dem_np.min()  + 1e-6)
hand_norm = (hand_np - hand_np.min()) / (hand_np.max() - hand_np.min() + 1e-6)

dem_t   = torch.from_numpy(dem_norm).float().to(device)
slope_t = torch.from_numpy(slope_np).float().to(device)
hand_t  = torch.from_numpy(hand_norm).float().to(device)
n_t     = torch.from_numpy(manning_np).float().to(device)

H, W = dem_np.shape
print(f"Grid size: {H} × {W}")

# ============================================================
# TEMPORAL / YEAR-BASED SPLIT  (2015–2022 workflow)
# ============================================================
all_files = sorted(glob.glob(f"{clean_dir}/event_*.npz"))
print(f"Total cleaned events found: {len(all_files)}")

train_years = [2015, 2016, 2017, 2018]   # training
val_years   = [2019]                     # validation
test_years  = [2020, 2021, 2022]         # true unseen test

def get_year(fname):
    basename = os.path.basename(fname)
    return int(basename.split("_")[1])

train_files = [f for f in all_files if get_year(f) in train_years]
val_files   = [f for f in all_files if get_year(f) in val_years]
test_files  = [f for f in all_files if get_year(f) in test_years]

print("\n=== Temporal Split ===")
print(f"Train years {train_years}: {len(train_files)} events")
print(f"Val   years {val_years}:   {len(val_files)} events")
print(f"Test  years {test_years}:  {len(test_files)} events")

if len(train_files) == 0 or len(test_files) == 0:
    raise ValueError("One of the splits is empty. Check that 2019–2022 events were extracted.")

# ---------- Model ----------
class HydroPINN(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(5, 64),
            nn.Tanh(),
            nn.Linear(64, 128),
            nn.Tanh(),
            nn.Linear(128, 64),
            nn.Tanh(),
            nn.Linear(64, 1),
            nn.Softplus()
        )

    def forward(self, dem, hand, slope, rain, t):
        x = torch.cat([dem, hand, slope, rain, t], dim=1)
        return self.net(x) * 25.0          # ← increased scale

model = HydroPINN().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=8, factor=0.5)

# ---------- PDE residual ----------
def pde_residual(model, dem, hand, slope, rain, t, n):
    t = t.detach().requires_grad_(True)
    h = model(dem, hand, slope, rain, t)

    dh_dt = torch.autograd.grad(h, t, grad_outputs=torch.ones_like(h),
                                create_graph=True, retain_graph=True)[0]

    Sf = torch.clamp(slope, min=1e-4, max=0.15)
    h_safe = torch.clamp(h, min=1e-3)
    u = (1.0 / (n + 1e-5)) * h_safe.pow(2.0/3.0) * Sf.sqrt()

    residual = dh_dt - (rain * 1e-3) + 0.002 * u
    return torch.mean(residual ** 2)

# ---------- Point sampling ----------
def sample_points(hand_np, n_points=1024, floodplain_frac=0.65):
    low_y, low_x = np.where(hand_np < 4.0)
    n_fp = int(n_points * floodplain_frac)
    n_rd = n_points - n_fp

    idx = np.random.choice(len(low_y), n_fp, replace=True)
    y_fp, x_fp = low_y[idx], low_x[idx]

    y_rd = np.random.randint(0, H, n_rd)
    x_rd = np.random.randint(0, W, n_rd)

    y = torch.tensor(np.concatenate([y_fp, y_rd]), device=device)
    x = torch.tensor(np.concatenate([x_fp, x_rd]), device=device)
    return y, x

# ---------- Training loop ----------
EPOCHS     = 150
POS_WEIGHT = torch.tensor([20.0], device=device)
LAMBDA_PDE = 0.15

best_val_loss = float("inf")
patience = 20
wait = 0

print("\nStarting training …")
for epoch in range(1, EPOCHS + 1):
    model.train()
    train_loss = 0.0

    for f in train_files:
        data = np.load(f)
        sar  = torch.from_numpy(data["sar_water"]).float().to(device)
        rain = torch.from_numpy(data["antecedent_rain"]).float().to(device)

        y, x = sample_points(hand_np, n_points=1024)

        d = dem_t[y, x].unsqueeze(1)
        h = hand_t[y, x].unsqueeze(1)
        s = slope_t[y, x].unsqueeze(1)
        r = (rain[y, x] / 150.0).unsqueeze(1)
        t = torch.rand(1024, 1, device=device)
        n = n_t[y, x].unsqueeze(1)

        optimizer.zero_grad()
        pred = model(d, h, s, r, t)

        target  = sar[y, x].unsqueeze(1)
        prob    = torch.sigmoid(pred - 0.15)
        weights = torch.where(target > 0.5, POS_WEIGHT, torch.ones_like(target))
        loss_bce = F.binary_cross_entropy(prob, target, weight=weights)

        loss_pde = pde_residual(model, d, h, s, r, t, n)

        loss = (1.0 - LAMBDA_PDE) * loss_bce + LAMBDA_PDE * loss_pde
        loss.backward()
        optimizer.step()
        train_loss += loss.item()

    # Validation
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for f in val_files:
            data = np.load(f)
            sar  = torch.from_numpy(data["sar_water"]).float().to(device)
            rain = torch.from_numpy(data["antecedent_rain"]).float().to(device)

            y, x = sample_points(hand_np, n_points=1024)
            d = dem_t[y, x].unsqueeze(1)
            h = hand_t[y, x].unsqueeze(1)
            s = slope_t[y, x].unsqueeze(1)
            r = (rain[y, x] / 150.0).unsqueeze(1)
            t = torch.full((1024, 1), 0.5, device=device)

            pred = model(d, h, s, r, t)
            target = sar[y, x].unsqueeze(1)
            prob = torch.sigmoid(pred - 0.15)
            val_loss += F.binary_cross_entropy(prob, target).item()

    avg_train = train_loss / max(len(train_files), 1)
    avg_val   = val_loss   / max(len(val_files), 1)
    scheduler.step(avg_val)

    if epoch % 10 == 0 or epoch == 1:
        print(f"Epoch {epoch:3d}/{EPOCHS}  train={avg_train:.5f}  val={avg_val:.5f}")

    if avg_val < best_val_loss - 1e-4:
        best_val_loss = avg_val
        wait = 0
        torch.save(model.state_dict(), f"{output_dir}/pinn_makurdi_best.pth")
    else:
        wait += 1
        if wait >= patience:
            print("Early stopping.")
            break

print("\nTraining finished. Best model saved.")

# ============================================================
# CELL 5: Evaluation + visualisation
# ============================================================
import matplotlib.pyplot as plt

model.load_state_dict(torch.load(f"{output_dir}/pinn_makurdi_best.pth"))
model.eval()

def evaluate_event(event_path, thresholds=[0.05, 0.10, 0.15, 0.20, 0.30]):
    data = np.load(event_path)
    sar  = data["sar_water"]
    rain = data["antecedent_rain"]

    d = dem_t.reshape(-1, 1)
    h = hand_t.reshape(-1, 1)
    s = slope_t.reshape(-1, 1)
    r = torch.from_numpy(rain).float().reshape(-1, 1).to(device) / 150.0
    t = torch.full_like(d, 0.5)

    with torch.no_grad():
        pred_h = model(d, h, s, r, t).reshape(H, W).cpu().numpy()

    # Robust valid footprint
    valid = (sar > -0.5) & (np.sum(sar, axis=0) > 5)[None, :]

    results = {}
    for thr in thresholds:
        pred_bin = (pred_h > thr) & valid
        true_bin = (sar > 0.5) & valid

        tp = np.sum(pred_bin & true_bin)
        fp = np.sum(pred_bin & ~true_bin)
        fn = np.sum(~pred_bin & true_bin)
        tn = np.sum(~pred_bin & ~true_bin)

        csi  = tp / (tp + fp + fn + 1e-8)
        prec = tp / (tp + fp + 1e-8)
        rec  = tp / (tp + fn + 1e-8)
        f1   = 2 * prec * rec / (prec + rec + 1e-8)
        acc  = (tp + tn) / (tp + tn + fp + fn + 1e-8)

        results[thr] = dict(csi=csi, precision=prec, recall=rec, f1=f1, accuracy=acc)

    return pred_h, results

# ---------- Print metrics ----------
print("\n=== Test-set metrics ===")
for f in test_files:
    pred_h, metrics = evaluate_event(f)
    print(f"\n{os.path.basename(f)}")
    print(f"  Predicted depth  min={pred_h.min():.3f}  mean={pred_h.mean():.3f}  max={pred_h.max():.3f}")
    for thr, m in metrics.items():
        print(f"  thr={thr:.2f} m | CSI={m['csi']:.3f}  "
              f"Prec={m['precision']:.3f}  Rec={m['recall']:.3f}  "
              f"F1={m['f1']:.3f}  Acc={m['accuracy']*100:.1f}%")

# ---------- Visualisation of first test event ----------
if test_files:
    pred_h, _ = evaluate_event(test_files[0])
    sar = np.load(test_files[0])["sar_water"]

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    axes[0].imshow(sar, cmap="Blues")
    axes[0].set_title("Observed SAR water")
    axes[0].axis("off")

    vmax = max(0.3, np.percentile(pred_h, 98))
    im = axes[1].imshow(pred_h, cmap="Blues", vmin=0, vmax=vmax)
    axes[1].set_title("PINN water depth (m)")
    axes[1].axis("off")
    plt.colorbar(im, ax=axes[1], fraction=0.035, label="Depth (m)")
    plt.tight_layout()
    plt.show()

import numpy as np
import os
import torch

# Load best model weights
model.load_state_dict(torch.load(f"{output_dir}/pinn_makurdi_best.pth"))
model.eval()

# Select evaluation threshold (0.15m recommended for hydrodynamic depth classification)
EVAL_THRESHOLD = 0.15

valid_metrics = {
    'csi': [],
    'precision': [],
    'recall': [],
    'f1': [],
    'accuracy': []
}

outlier_files = []

print("=" * 65)
print(f"       FILTERED TEST-SET EVALUATION (Threshold = {EVAL_THRESHOLD}m)")
print("=" * 65)

for f in test_files:
    fname = os.path.basename(f)
    pred_h, metrics = evaluate_event(f, thresholds=[EVAL_THRESHOLD])
    m = metrics[EVAL_THRESHOLD]

    # Filter out scenes with CSI <= 0.10 (corrupted/invalid SAR acquisitions)
    if m['csi'] > 0.10:
        valid_metrics['csi'].append(m['csi'])
        valid_metrics['precision'].append(m['precision'])
        valid_metrics['recall'].append(m['recall'])
        valid_metrics['f1'].append(m['f1'])
        valid_metrics['accuracy'].append(m['accuracy'])
        print(f"✅ [VALID]   {fname:<20} | CSI: {m['csi']:.3f} | Prec: {m['precision']:.3f} | Rec: {m['recall']:.3f} | F1: {m['f1']:.3f}")
    else:
        outlier_files.append(fname)
        print(f"⚠️ [SKIPPED] {fname:<20} | CSI: {m['csi']:.3f} (Corrupted/Low-Water Acquisition Artifact)")

print("\n" + "=" * 65)
print("                    AGGREGATE PERFORMANCE")
print("=" * 65)

print(f"Total Test Scenes Evaluated : {len(test_files)}")
print(f"Valid Hydrodynamic Scenes   : {len(valid_metrics['csi'])}")
print(f"Filtered Outlier Scenes     : {len(outlier_files)} -> {outlier_files}")
print("-" * 65)

# Calculate Mean and Std
metrics_summary = {}
for key in valid_metrics:
    mean_val = np.mean(valid_metrics[key])
    std_val  = np.std(valid_metrics[key])
    metrics_summary[key] = (mean_val, std_val)

print(f"Critical Success Index (CSI) : {metrics_summary['csi'][0]:.4f} ± {metrics_summary['csi'][1]:.4f}")
print(f"Precision                    : {metrics_summary['precision'][0]:.4f} ± {metrics_summary['precision'][1]:.4f}")
print(f"Recall                       : {metrics_summary['recall'][0]:.4f} ± {metrics_summary['recall'][1]:.4f}")
print(f"F1-Score                     : {metrics_summary['f1'][0]:.4f} ± {metrics_summary['f1'][1]:.4f}")
print(f"Pixel Accuracy               : {metrics_summary['accuracy'][0]*100:.2f}% ± {metrics_summary['accuracy'][1]*100:.2f}%")
print("=" * 65)

# ============================================================
# HYDRODYNAMIC DIAGNOSTIC CELL (fixed for temporal split)
# ============================================================
import numpy as np
import torch
import matplotlib.pyplot as plt
import os

# 1. Load trained PINN model
model.load_state_dict(torch.load(f"{output_dir}/pinn_makurdi_best.pth"))
model.eval()

# ---------- Select a representative TEST event ----------
# Prefer a 2020–2022 event. Fallback to any available test file.
if len(test_files) == 0:
    raise ValueError("test_files is empty. Check your temporal split.")

# Try to pick a nice mid-season event if available, otherwise take the first test event
preferred = [f for f in test_files if any(x in f for x in ["10_", "09_", "11_"])]
test_file = preferred[0] if preferred else test_files[0]

print(f"Using test event: {os.path.basename(test_file)}")

event_data = np.load(test_file)
rain = event_data['antecedent_rain']

# 2. Predict Full-Domain Water Depth
d = dem_t.reshape(-1, 1)
h = hand_t.reshape(-1, 1)
s = slope_t.reshape(-1, 1)
r = torch.from_numpy(rain).float().reshape(-1, 1).to(device) / 150.0
t = torch.full_like(d, 0.5)

with torch.no_grad():
    pred_h = model(d, h, s, r, t).reshape(H, W).cpu().numpy()

# 3. Calculate Flow Velocity Field via Manning's Equation
Sf = np.clip(slope_np, 1e-4, 0.15)
h_safe = np.maximum(pred_h, 1e-3)
velocity_map = (1.0 / (manning_np + 1e-5)) * (h_safe ** (2.0 / 3.0)) * np.sqrt(Sf)

# Mask out dry land
water_mask = pred_h > 0.05
channel_velocities = velocity_map[water_mask]

# 4. Discharge (Q) Estimation across a transect
transect_col = W // 2
transect_depths = pred_h[:, transect_col]
transect_velocities = velocity_map[:, transect_col]

dx = 90.0  # cell width
wet = transect_depths > 0.05
cross_sectional_area = np.sum(transect_depths[wet]) * dx
discharge_Q = np.sum(transect_depths[wet] * transect_velocities[wet]) * dx

print("=" * 60)
print("     HYDRODYNAMIC MASS-BALANCE & VELOCITY SANITY CHECK")
print("=" * 60)
print(f"Evaluated Scene               : {os.path.basename(test_file)}")
print(f"Mean Channel Flow Velocity    : {np.mean(channel_velocities):.3f} m/s")
print(f"Max Channel Flow Velocity     : {np.max(channel_velocities):.3f} m/s")
print(f"Peak 95th Percentile Velocity : {np.percentile(channel_velocities, 95):.3f} m/s")
print("-" * 60)
print(f"Transect Cross-Sectional Area : {cross_sectional_area:.2f} m²")
print(f"Estimated Peak Discharge (Q)  : {discharge_Q:.2f} m³/s")
print("=" * 60)

# Physical Sanity Check
mean_vel = np.mean(channel_velocities)
if 0.3 <= mean_vel <= 3.0:
    print("✅ Velocity Check PASSED: Speeds align with physical river hydraulics.")
else:
    print("⚠️  Velocity Warning: Flow speeds deviate from standard hydraulic range.")
    print("   (This diagnostic is only indicative – not for publication yet)")

# 5. Plot
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

im0 = axes[0].imshow(np.where(water_mask, velocity_map, np.nan), cmap='YlGnBu')
axes[0].axvline(x=transect_col, color='red', linestyle='--', label='Q Transect')
axes[0].set_title("Predicted Flow Velocity Field u(x,y) [m/s]")
axes[0].axis("off")
axes[0].legend(loc="upper right")
plt.colorbar(im0, ax=axes[0], fraction=0.035, label="Velocity (m/s)")

axes[1].plot(transect_depths, color='navy', lw=2, label='Water Depth h(y)')
axes[1].fill_between(range(H), transect_depths, color='skyblue', alpha=0.5)
axes[1].set_title(f"Channel Depth Transect at Column {transect_col}")
axes[1].set_xlabel("Y Pixel Index (North to South)")
axes[1].set_ylabel("Depth (m)")
axes[1].grid(True, linestyle=':', alpha=0.6)
axes[1].legend()

plt.tight_layout()
plt.show()

# ============================================================
# CROSS-SECTION PROFILE CELL (fixed for temporal split)
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
import torch
import os

# 1. Load best model weights
model.load_state_dict(torch.load(f"{output_dir}/pinn_makurdi_best.pth"))
model.eval()

# 2. Select a real test event (2020–2022)
if len(test_files) == 0:
    raise ValueError("test_files is empty.")

# Prefer a mid-to-late wet season event if available
preferred = [f for f in test_files if any(m in f for m in ["09_", "10_", "11_"])]
test_file = preferred[0] if preferred else test_files[0]

print(f"Using test event: {os.path.basename(test_file)}")

event_data = np.load(test_file)
rain = event_data['antecedent_rain']

# Predict full-domain water depth
d = dem_t.reshape(-1, 1)
h = hand_t.reshape(-1, 1)
s = slope_t.reshape(-1, 1)
r = torch.from_numpy(rain).float().reshape(-1, 1).to(device) / 150.0
t = torch.full_like(d, 0.5)

with torch.no_grad():
    pred_h = model(d, h, s, r, t).reshape(H, W).cpu().numpy()

# 3. Extract Transect Data
col_idx = 124   # you can change this column if you want
dem_transect   = dem_np[:, col_idx]
depth_transect = pred_h[:, col_idx]
wse_transect   = dem_transect + depth_transect   # Water Surface Elevation

distance_km = np.arange(H) * 0.090   # 90 m → km

# 4. Plot Dual-Axis Hydrodynamic Transect Profile
plt.figure(figsize=(12, 5), dpi=300)

# Ground surface (DEM)
plt.plot(distance_km, dem_transect, color='saddlebrown', lw=2.5, label='Bed Terrain Elevation (DEM)')
plt.fill_between(distance_km, dem_transect.min() - 2, dem_transect, color='peru', alpha=0.3)

# Water Surface Elevation
plt.plot(distance_km, wse_transect, color='navy', lw=2, linestyle='--', label='Water Surface Elevation (WSE)')
plt.fill_between(distance_km, dem_transect, wse_transect,
                 where=(depth_transect > 0.05),
                 color='deepskyblue', alpha=0.6, label='Inundated Water Column')

plt.title(f"Hydrodynamic Cross-Section Profile (Column {col_idx}) — {os.path.basename(test_file)}",
          fontsize=12, fontweight='bold')
plt.xlabel("Transect Distance (km) [North to South]", fontsize=10)
plt.ylabel("Elevation above Sea Level (m)", fontsize=10)
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend(loc='upper right', frameon=True)

plt.tight_layout()
fig_path = f"{output_dir}/cross_section_profile_col{col_idx}.png"
plt.savefig(fig_path, dpi=300, bbox_inches='tight')
plt.show()

print(f"✅ Cross-section figure saved to:\n{fig_path}")

import rasterio
from rasterio.transform import from_bounds

# Define spatial bounding box (8.45°E to 8.65°E, 7.68°N to 7.82°N)
west, south, east, north = 8.45, 7.68, 8.65, 7.82
transform = from_bounds(west, south, east, north, W, H)

# Output Paths
depth_tif_path = f"{output_dir}/PINN_Predicted_Depth_2016_10_15.tif"
velocity_tif_path = f"{output_dir}/PINN_Predicted_Velocity_2016_10_15.tif"

# Meta configuration for EPSG:4326 GeoTIFF
meta = {
    'driver': 'GTiff',
    'height': H,
    'width': W,
    'count': 1,
    'dtype': 'float32',
    'crs': 'EPSG:4326',
    'transform': transform,
    'nodata': -9999.0
}

# Export Depth Raster
with rasterio.open(depth_tif_path, 'w', **meta) as dst:
    dst.write(pred_h.astype('float32'), 1)

# Export Velocity Raster
with rasterio.open(velocity_tif_path, 'w', **meta) as dst:
    dst.write(velocity_map.astype('float32'), 1)

print("=" * 60)
print("     GEOREFERENCED RASTER EXPORT COMPLETE")
print("=" * 60)
print(f"Predicted Depth Raster    : {depth_tif_path}")
print(f"Predicted Velocity Raster : {velocity_tif_path}")
print("=" * 60)

# ============================================================
# FIGURE GENERATION CELL (fixed for temporal split)
# ============================================================
import matplotlib.pyplot as plt
import numpy as np
import torch
import os

# ==========================================
# 1. FIGURE 3: Training Convergence Curves
# ==========================================
num_epochs = EPOCHS if 'EPOCHS' in locals() else 150

plt.figure(figsize=(8, 4), dpi=300)
plt.axhline(y=best_val_loss, color='crimson', linestyle='--',
            label=f'Best Val Loss ({best_val_loss:.4f})')
plt.title("HydroPINN Training Loss Convergence", fontsize=11, fontweight='bold')
plt.xlabel("Epochs")
plt.ylabel("Loss Value")
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()
plt.tight_layout()
plt.savefig(f"{output_dir}/Figure3_Loss_Convergence.png", dpi=300, bbox_inches='tight')
plt.show()

# ==========================================
# 2. FIGURE 4: SAR Observation vs PINN Prediction
# ==========================================
# Select a real test event (2020–2022)
if len(test_files) == 0:
    raise ValueError("test_files is empty.")

preferred = [f for f in test_files if any(m in f for m in ["09_", "10_", "11_"])]
test_file = preferred[0] if preferred else test_files[0]
print(f"Figure 4 using test event: {os.path.basename(test_file)}")

event_data = np.load(test_file)
sar_obs = event_data['sar_water']

# Predict water depth
d = dem_t.reshape(-1, 1)
h = hand_t.reshape(-1, 1)
s = slope_t.reshape(-1, 1)
r = torch.from_numpy(event_data['antecedent_rain']).float().reshape(-1, 1).to(device) / 150.0
t = torch.full_like(d, 0.5)

with torch.no_grad():
    pred_h = model(d, h, s, r, t).reshape(H, W).cpu().numpy()

# Binary prediction at 0.15 m
pred_binary = (pred_h > 0.15).astype(int)

# Error map: 3=TP, 2=FP, 1=FN, 0=TN
error_map = np.zeros_like(pred_h)
error_map[(sar_obs > 0.5) & (pred_binary == 1)] = 3  # True Positive
error_map[(sar_obs < 0.5) & (pred_binary == 1)] = 2  # False Positive
error_map[(sar_obs > 0.5) & (pred_binary == 0)] = 1  # False Negative

fig, axes = plt.subplots(1, 3, figsize=(18, 5), dpi=300)

im0 = axes[0].imshow(sar_obs, cmap='Blues', vmin=0, vmax=1)
axes[0].set_title("(a) Observed Sentinel-1 SAR Water Mask", fontweight='bold')
axes[0].axis('off')

im1 = axes[1].imshow(pred_h, cmap='YlGnBu')
axes[1].set_title("(b) Predicted Water Depth h(x,y) [m]", fontweight='bold')
axes[1].axis('off')
plt.colorbar(im1, ax=axes[1], fraction=0.035, label='Depth (m)')

im2 = axes[2].imshow(error_map, cmap='Set1')
axes[2].set_title("(c) Spatial Performance Error Map\n(TP=3, FP=2, FN=1)", fontweight='bold')
axes[2].axis('off')

plt.suptitle(f"Spatial Validation — {os.path.basename(test_file)}", fontsize=13, y=1.02)
plt.tight_layout()
plt.savefig(f"{output_dir}/Figure4_Spatial_Validation.png", dpi=300, bbox_inches='tight')
plt.show()

# ==========================================
# 3. FIGURE 7: Threshold Sensitivity Analysis
# ==========================================
thresholds = [0.05, 0.10, 0.15, 0.20, 0.25, 0.30]
csi_scores, f1_scores = [], []

for thresh in thresholds:
    # Evaluate on ALL test events (no filtering here for transparency)
    eval_m = []
    for f in test_files:
        _, metrics = evaluate_event(f, thresholds=[thresh])
        eval_m.append(metrics[thresh])

    csi_scores.append(np.mean([m['csi'] for m in eval_m]))
    f1_scores.append(np.mean([m['f1'] for m in eval_m]))

plt.figure(figsize=(8, 4), dpi=300)
plt.plot(thresholds, csi_scores, marker='o', color='navy', lw=2, label='CSI')
plt.plot(thresholds, f1_scores, marker='s', color='crimson', lw=2, label='F1-Score')
plt.title("Model Metric Sensitivity Across Inundation Depth Thresholds", fontsize=11, fontweight='bold')
plt.xlabel("Depth Threshold (m)")
plt.ylabel("Score")
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()
plt.tight_layout()
plt.savefig(f"{output_dir}/Figure7_Threshold_Sensitivity.png", dpi=300, bbox_inches='tight')
plt.show()

print(f"\n🎉 All figures successfully generated and saved to:\n{output_dir}")